### ISSUE TITLE
+5  or variable volume steps

### ISSUE THREAD

**Issue by flybob8888** [jordenc/com.onkyo#26]
Instead of only +-1, can it be variable or largers steps as well?
Onkyo don't seem to appreciate sending 20 x +1 volume steps at once and annoying to press buttons at home many times, would be nice with such an option.

**Comment by jordenc** [comment]
I think there is a tag in Homey that represents the current volume. You might be able to use that to set it to +5.

The Onkyo app has been adopted by Mickel Luiten, since I don't own an Onkyo receiver  anymore. You might have more luck posting an issue here: https://github.com/mickelluiten/com.onkyo
