### ISSUE TITLE
Onkyo App does not detect if my Onkyo is on (card keeps greyed out)

### ISSUE THREAD

**Issue by spoelly** [jordenc/com.onkyo#4]
What is you version (Settings → System)?
1.1.1

What did you try to achieve?
mute onkyo when i start talking to homey and unmute when i stop talking when the onkyo is used. 

What was the result?
nothing happens

What did you expect as result?
that the onkyo mutes when talking to homey and unmutes when i stop talking.

Any other remarks
The Onkyo app does not detect anymore that the Onkyo is on. This way my mute/unmute flow always fails. The app card is greyed out only when i click it is becomes active and the flows work.

**Comment by spoelly** [comment]
After firmware 1.3 rc7 the Onkyo app works again.. will test some more!

**Comment by jordenc** [comment]
Good to hear!

It might be that your Onkyo had closed its connection to Homey. That happens sometimes although I am still unable to figure out how to detect that and reconnect. It's kinda hard to test for me because it doesn't happen so often, it runs for weeks without problems here.
If it happens, a software update on Homey (= reboot of the app), reboot of Homey or disabling and enabling of the app will probably solve it.

**Comment by spoelly** [comment]
Thanks, running smooth ever since.
