### ISSUE TITLE
Feature: Add polling

### ISSUE THREAD

**Issue by jjtbsomhorst** [jordenc/com.onkyo#6]
Hi, 

today I noticed that when you manually switch a channel or the volume the homey app doesn't pick this up. It would be a nice feature to let the app poll the onkyo to see if something has changed from outside homey.

**Comment by jordenc** [comment]
I need to do a rewrite soon, but it should work without polling.

The app opens a connection to the Onkyo, and keeps that open. Every command you send, even with the remote control, will be passed through to Homey. However, sometimes the connection gets stuck and Homey will not reconnect. This happens to me after a few weeks and will not be solved until I restart Homey (I think). Kinda hard to debug it because of that.
Still need to convert this app to a Homey SDK v2 version and will see if I can fix this "disconnect" issue then as well.
